### ISSUE TITLE
file_extension in kernel_info_reply should be "py" not ".py"

### ISSUE THREAD

**Issue by zmughal** [ipython/ipython_kernel#12]
The `kernel_info_reply` lists the `file_extension` field in the `language_info` dictionary as
```python
                     'file_extension': '.py'
```
but according to the [messaging spec](http://ipython.org/ipython-doc/dev/development/messaging.html#kernel-info), it should just be `'py'`:
```python
        # Extension without the dot, e.g. 'py'
        'file_extension': str,
```

<https://github.com/ipython/ipython_kernel/blob/157009624cb2954e30e724bc3edf9b9c2486b8d4/ipython_kernel/ipkernel.py#L110>

**Comment by minrk** [comment]
It's true there's a mismatch, but it's actually the doc that needs updating. It should include the '.'.
