### ISSUE TITLE
Don't reference ipython_widgets.

### ISSUE THREAD

**Issue by jdfreder** [ipython/ipython_kernel#9]
Right now `ipython_widgets` is referenced as `IPython.html.widgets`.   We should be referencing it at all.  Instead the kernel should provide means for specifying Python extensions on to be loaded with the kernel.  The widgets would use this.

**Comment by Carreau** [comment]
so do you want IPython it self to shim and warn if people import IPython.html.widgets ?

**Comment by minrk** [comment]
@jdfreder why does it need to do anything on load? Can't it trigger on import?

**Comment by jdfreder** [comment]
@Carreau no shim, I want a configurable traitlet like `extensions = List(Classes)` or something more complex, like @takluyver 's nbextensions API.

@minrk that could work..  The point of this hook is to allow the widgets to register a comm callback, so widgets can be created from the front-end without the need to execute Python.  If we make the decision that that doesn't make sense to do, then hook on import is fine.

**Comment by jdfreder** [comment]
But referencing ipython_widgets in ipython_kernel I think we can all agree is not right. : )

**Comment by minrk** [comment]
@jdfreder IPython has extensions - this is what all the other extensions are based on:

    c.TerminalIPythonApp.extensions = ['myext']
